name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Install packages
        uses: borales/actions-yarn@v2.0.0
      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
      - name: Export to out dir
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out